apiVersion: "keptn.sh/v1"
kind: "KeptnService"
metadata:
  name: "podtatohead"
spec:
  project: "podtato-head"
  service: "podtatohead"
  deploymentEvent: "artifact-delivery.triggered"

---
apiVersion: "keptn.sh/v1"
kind: "KeptnServiceDeployment"
metadata:
  name: "podtatohead-dev"
spec:
  project: "podtato-head"
  service: "podtatohead"
  stage: "dev"
  version: "0.0.48"
