apiVersion: v2
actions:
  - name: "Deploy using helm"
    events:
      - name: "sh.keptn.event.deployment.triggered"
    tasks:
      - name: "Run helm"
        files:
          - /helm
        env:
          - name: SERVICE
            value: "$.data.service"
            valueFrom: event
        image: "alpine/helm:3.8.0"
        cmd: ["helm"]
        args: ["upgrade", "--create-namespace", "--install", "--atomic", "-n", "$(SERVICE)", "$(SERVICE)", "/keptn/helm/$(SERVICE)/.", "--wait"]
  - name: "k6-smoke"
    events:
      - name: "sh.keptn.event.smoke-test.triggered"
    tasks:
      - name: "k6"
        files:
          - /k6
        image: "loadimpact/k6"
        cmd: ["k6"]
        args: ["run", "-e", "SERVICE=$(SERVICE)", "--duration", "60s", "--vus", "30", "/keptn/k6/smoke.js"]
        env:
          - name: SERVICE
            value: "$.data.service"
            valueFrom: event
  - name: "release"
    events:
      - name: "sh.keptn.event.release.triggered"
    tasks:
      - name: "argo-promote"
        image: "quay.io/argoproj/kubectl-argo-rollouts:master"
        args: ["promote","$(SERVICE)","-n","$(SERVICE)"]
        env:
          - name: SERVICE
            value: "$.data.service"
